# Generated by Django 6.0.3 on 2026-04-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug_app', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorsolution',
            name='tag',
        ),
        migrations.AddField(
            model_name='errorsolution',
            name='tags',
            field=models.CharField(default='general', max_length=200),
            preserve_default=False,
        ),
    ]
