# Generated by Django 6.0.3 on 2026-04-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug_app', '0003_remove_errorsolution_tag_errorsolution_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorsolution',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
