# Generated by Django 6.0.3 on 2026-04-10 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug_app', '0004_alter_errorsolution_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorsolution',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='errorsolution',
            name='tags',
        ),
        migrations.AlterField(
            model_name='errorsolution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='errorsolution',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='errors', to='debug_app.tag'),
        ),
    ]
